language: java

jdk:
  - openjdk8

branches:
  only:
    - development

before_script:
  - ls -la # this command just prints the contents of the current working directory.

script:
  - mvn clean package jacoco:report cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 816cefd1-ec03-43b0-bc9b-e1374106ac7c