language: java

jdk:
  - openjdk8

branches:
  only:
    - development

before_script:
  - ls -la # this command just prints the contents of the current working directory.

script:
  - mvn clean package jacoco:report cobertura:cobertura

after_success:
  - echo "Process terminated successfully"