language: java

jdk:
  - openjdk8

branches:
  only:
    - development

before_script:
  - cd Lab_Assignments  # enter Maven root directory
  - ls -la # this command just prints the contents of the current working directory.

script:
  - mvn clean package

after_success:
  - echo "Process terminated successfully"